<a href="https://colab.research.google.com/github/iean3124/coding_test/blob/main/report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def fact(n):
  if n==0:
    return 1
  else:
    return n*fact(n-1)
print(fact(5))

120


In [ ]:
names=['Corey','Chrisa','Dave','Travis','Smith']
for index, name in enumerate(names,start=1):
    print(index,name)

1 Corey
2 Chrisa
3 Dave
4 Travis
5 Smith


In [ ]:
names=['Peter Parker','clark Kent','Wade Wilson','Bruce Wayne']
heroes=['Spiderman','Superman','Deadpool','Batman']
for name, hero in zip(names,heroes):
    print(f'{name} is actually {hero}')

Peter Parker is actually Spiderman
clark Kent is actually Superman
Wade Wilson is actually Deadpool
Bruce Wayne is actually Batman


In [ ]:
class Car:
    def __init__(self,color,speed):
        self.color=color
        self.speed= speed
    def speedUp(self,v):
        self.speed=self.speed+v
        return self.speed 
    def speedDown(self,v):
        self.speed=self.speed-v 
        return self.speed 
myCar=Car('Black',60)
print('색상: ',myCar.color,'속도: ',myCar.speed)
myCar.color='Red'
print('색상: ',myCar.color)
myCar.speedUp(10)
print('속도: ',myCar.speed)
myCar.speedDown(20)
print('속도: ',myCar.speed)

색상:  Black 속도:  60
색상:  Red
속도:  70
속도:  50


In [ ]:
A=[1,0]

B=[[1,1],[1,0]]
print(A+B)

[1, 0, [1, 1], [1, 0]]


In [ ]:
import numpy as np
A = np.array([[1,0],[0,1]])
B = np.array([[1,1],[1,1]])
A + B

array([[2, 1],
       [1, 2]])

In [ ]:
import numpy as np

A=np.array([1,2,3])
B= np.array([4,5,6])
print("A==",A,',B==',B)
print("vector A shape ==",A.shape,',vector B shape==',B.shape)
print("vector A dimenson ==", A.ndim,", vector B doimension ==",B.ndim)

A== [1 2 3] ,B== [4 5 6]
vector A shape == (3,) ,vector B shape== (3,)
vector A dimenson == 1 , vector B doimension == 1


In [ ]:
import numpy as np
A= np.array([[1,2,3],[2,4,6]])
B=np.array([[-1,-2,-3],[-4,-5,-6]])

print('matrix A= ',A)
print('matrinx B= ',B)
print("matrix A shape==",A.shape,", matrix B shape ==",B.shape)
print("matrix A dimemsion == ",A.ndim,", matrix B dimension ==",B.ndim)

matrix A=  [[1 2 3]
 [2 4 6]]
matrinx B=  [[-1 -2 -3]
 [-4 -5 -6]]
matrix A shape== (2, 3) , matrix B shape == (2, 3)
matrix A dimemsion ==  2 , matrix B dimension == 2


In [ ]:
import numpy as np
A=np.array([1,2,3])
B=np.array([4,5,6])

print("A==",A,",B== ",B)
print("A+B== ",A+B)
print("A-b==",A-B)
print("A*B==",A*B)
print("A/B== ",A/B)

A== [1 2 3] ,B==  [4 5 6]
A+B==  [5 7 9]
A-b== [-3 -3 -3]
A*B== [ 4 10 18]
A/B==  [0.25 0.4  0.5 ]


In [ ]:
import numpy as np
C=np.array([1,2,3])
print("C.shape ==",C.shape)

C=C.reshape(1,3)
print ("C.shape ==",C.shape)

D=np.array([[1,2,3],[4,5,6]])
print("D.shape ==",D.shape)

D=D.reshape(3,2)
print("D.shape ==",D.shape)

C.shape == (3,)
C.shape == (1, 3)
D.shape == (2, 3)
D.shape == (3, 2)


In [ ]:
import numpy as np
A= np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400]])
print(A.shape)
B= A.reshape(-1,3)
print('B.shape = ',B.shape)
print(B)

C =  A.reshape(-1,6)
print('C.shape = ',C.shape)
print(C)

(3, 4)
B.shape =  (4, 3)
[[  1   2   3]
 [  4  10  20]
 [ 30  40 100]
 [200 300 400]]
C.shape =  (2, 6)
[[  1   2   3   4  10  20]
 [ 30  40 100 200 300 400]]


In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=5
print(A+B)

C=np.array([[1,2],[3,4]])
D=np.array([4,5])
print (C+D)


[[6 7]
 [8 9]]
[[5 7]
 [7 9]]


In [ ]:
import numpy as np

A=np.array([[1,2],[3,4],[5,6]])
B=A.T

print('A.shape = ',A.shape)
print('B.shape =',B.shape)
print(A)
print(B)

A.shape =  (3, 2)
B.shape = (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
